### ISSUE TITLE
Cluster node naming conventions

### ISSUE THREAD

**Issue by m-wynn** [utdlug/lug-cloud#1]
compute09 is a really boring name.

There are a few decent options:
- Composers/Musicians of some time period, alphabetically
- LUG alumni, sorted by amount of money donated
- Rocks
- Fast food restaurants
- Cities in the Ukraine
- Roman emperors by year
- Non-UTF-8 IKEA furniture names
- [Runes](https://namingschemes.com/Runes)
- Pizza toppings
- Prisons
- Tanks
- UNIX kill signals :smiley: 

Feel free to suggest more in the comments below!

**Comment by the-maldridge** [comment]
While I am a fan of your second suggested naming convention, the bigger priority is to get the system reliably online.
